run:
  timeout: 5m
  tests: true
  modules-download-mode: readonly

linters-settings:
  govet:
    shadow: true
  gocyclo:
    min-complexity: 25
  dupl:
    threshold: 150
  goconst:
    min-len: 4
    min-occurrences: 4
  misspell:
    locale: US
  lll:
    line-length: 160
  goimports:
    local-prefixes: github.com/lanixx/runfromyaml
  gocritic:
    enabled-tags:
      - diagnostic
      - performance
    disabled-checks:
      - dupImport
      - ifElseChain
      - octalLiteral
      - whyNoLint
      - wrapperFunc
      - commentFormatting
      - paramTypeCombine
      - commentedOutCode
      - rangeValCopy
      - emptyStringTest
      - exitAfterDefer
      - appendAssign
      - unnamedResult
      - equalFold
  gosec:
    excludes:
      - G304
      - G306
      - G204
      - G115
      - G302

linters:
  enable:
    - errcheck
    - gofmt
    - goimports
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
  disable:
    # Disable overly strict linters for now
    - depguard
    - dupl
    - goconst
    - gocritic
    - gocyclo
    - gosec
    - exhaustive
    - lll
    - stylecheck
    - unparam
    - whitespace

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - gosec
        - goconst
        - unparam
        - dupl
    - path: main\.go
      linters:
        - gochecknoinits
    - text: "Error return value.*is not checked"
      linters:
        - errcheck
    - text: "should have comment"
      linters:
        - stylecheck
    - text: "package comment"
      linters:
        - stylecheck
  exclude-use-default: true
  max-issues-per-linter: 20
  max-same-issues: 5
