on: release
name: Build Release
jobs:
  release-linux-386:
    name: "release linux/386"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: compile and release
      uses: wangyoucao577/go-release-action@v1.20
      with:
        github_token: ${{ secrets.MY_GITHUB_TOKEN }}
        goos: linux
        goarch: 386
        goversion: 1.17
        binary_name: runfromyaml
        asset_name: ${BINARY_NAME}-${RELEASE_TAG}-Linux-i686
  release-linux-amd64:
    name: "release linux/amd64"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: compile and release
      uses: wangyoucao577/go-release-action@v1.20
      with:
        github_token: ${{ secrets.MY_GITHUB_TOKEN }}
        goos: linux
        goarch: amd64
        goversion: 1.17
        binary_name: runfromyaml
        asset_name: ${BINARY_NAME}-${RELEASE_TAG}-Linux-x86_64
  release-linux-arm:
    name: "release linux/arm"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: compile and release
      uses: wangyoucao577/go-release-action@v1.20
      with:
        github_token: ${{ secrets.MY_GITHUB_TOKEN }}
        goos: linux
        goarch: arm
        goversion: 1.17
        binary_name: runfromyaml
        asset_name: ${BINARY_NAME}-${RELEASE_TAG}-Linux-armvXl
  release-linux-arm64:
    name: "release linux/arm64"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: compile and release
      uses: wangyoucao577/go-release-action@v1.20
      with:
        github_token: ${{ secrets.MY_GITHUB_TOKEN }}
        goos: linux
        goarch: arm64
        goversion: 1.17
        binary_name: runfromyaml
        asset_name: ${BINARY_NAME}-${RELEASE_TAG}-Linux-arm64
  release-darwin-amd64:
    name: "release darwin/amd64"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: compile and release
      uses: wangyoucao577/go-release-action@v1.20
      with:
        github_token: ${{ secrets.MY_GITHUB_TOKEN }}
        goos: darwin
        goarch: amd64
        goversion: 1.17
        binary_name: runfromyaml
        asset_name: ${BINARY_NAME}-${RELEASE_TAG}-Darwin-amd64
  release-darwin-arm64:
    name: "release darwin/arm64"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: compile and release
      uses: wangyoucao577/go-release-action@v1.20
      with:
        github_token: ${{ secrets.MY_GITHUB_TOKEN }}
        goos: darwin
        goarch: arm64
        goversion: 1.17
        binary_name: runfromyaml
        asset_name: ${BINARY_NAME}-${RELEASE_TAG}-Darwin-arm64
  release-windows-386:
    name: "release windows/386"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: compile and release
      uses: wangyoucao577/go-release-action@v1.20
      with:
        github_token: ${{ secrets.MY_GITHUB_TOKEN }}
        goos: windows
        goarch: 386
        goversion: 1.17
        binary_name: runfromyaml
        asset_name: ${BINARY_NAME}-${RELEASE_TAG}-Windows-i686
  release-windows-amd64:
    name: "release windows/amd64"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: compile and release
      uses: wangyoucao577/go-release-action@v1.20
      with:
        github_token: ${{ secrets.MY_GITHUB_TOKEN }}
        goos: windows
        goarch: amd64
        goversion: 1.17
        binary_name: runfromyaml
        asset_name: ${BINARY_NAME}-${RELEASE_TAG}-Windows-x86_64
