on: release
name: Build Release
jobs:
  release:
    name: "Build multi-platform release"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - goos: linux
            goarch: 386
            asset_name: runfromyaml-Linux-i686
          - goos: linux
            goarch: amd64
            asset_name: runfromyaml-Linux-x86_64
          - goos: linux
            goarch: arm
            asset_name: runfromyaml-Linux-armvXl
          - goos: linux
            goarch: arm64
            asset_name: runfromyaml-Linux-arm64
          - goos: darwin
            goarch: amd64
            asset_name: runfromyaml-Darwin-x86_64
          - goos: darwin
            goarch: arm64
            asset_name: runfromyaml-Darwin-arm64
          - goos: windows
            goarch: 386
            asset_name: runfromyaml-Windows-i686
          - goos: windows
            goarch: amd64
            asset_name: runfromyaml-Windows-x86_64
    steps:
    - uses: actions/checkout@master
    - name: compile and release
      uses: wangyoucao577/go-release-action@v1.51
      with:
        github_token: ${{ secrets.MY_GITHUB_TOKEN }}
        goos: ${{ matrix.goos }}
        goarch: ${{ matrix.goarch }}
        goversion: 1.25.1
        binary_name: runfromyaml
        asset_name: ${{ matrix.asset_name }}
